### ISSUE TITLE
With the minimal config file, I get "retrieving _ not supported for typescript"

### ISSUE THREAD

**Issue by jyc** [ryanolsonx/vim-lsp-typescript#3]
Happy to provide more debugging information, but I am stumped as to why this could be happening even with the minimal config file provided in the README.

**Comment by ryanolsonx** [comment]
I'll dig into it. Are you running on linux/mac/windows?

**Comment by ryanolsonx** [comment]
Can you send me the output of `npm list -g --depth=0 | grep typescript`?

**Comment by jyc** [comment]
Hey! Thanks! Here's the output with the command:

```
[jyc@jc-fig1-osx ~]
→ npm list -g --depth=0 | grep typescript
├── typescript@3.2.2
└── typescript-language-server@0.3.7
```

**Comment by ryanolsonx** [comment]
I tested out the minimal config file and things are working fine for me. Can you post a screenshot of where you're seeing the error?

**Comment by jyc** [comment]
Sure! I took a recording using asciinema so that I could capture everything I did: https://asciinema.org/a/m1DyHt1EzI3FzcRyYy2DpMyLs

I'm starting to wonder if I have just installed something wrong. I don't normally write TypeScript and I haven't touched my vim stuff in earnest in a few years.

One weird thing I noticed is that with the minimal vimrc it looks like the .ts file is initially seen as xml. Another gotcha is perhaps that I am running neovim.

**Comment by ryanolsonx** [comment]
@jyc Let me know if the solution works for you.

**Comment by jyc** [comment]
@ryanolsonx It works perfectly now! This is amazing!

Thanks for the help and for the software. Nice to have an option other than VS Code that I can recommend to my coworkers :) Have a great rest of your week!

**Comment by ryanolsonx** [comment]
No problem! Have a good day.
